name: "MNCD"

trigger:
  - master

pr:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"

stages:
- stage: build
  displayName: Build
  jobs:
    - job: build 
      displayName: Build
      steps:
          - task: DotNetCoreCLI@2
            displayName: "dotnet build $(buildConfiguration)"
            inputs:
              command: "build"
              arguments: --configuration $(buildConfiguration)
              workingDirectory: src
              
- stage: test
  displayName: Test
  dependsOn: build
  jobs:
    - job: test
      displayName: Test
      steps:
          - task: DotNetCoreCLI@2
            displayName: "dotnet test"
            inputs:
              command: "test"
              workingDirectory: src

- stage: pack_and_publish
  displayName: Pack & Publish Nuget
  dependsOn: test
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - job: pack_and_publish
      displayName: Pack & Publish Nuget
      steps:
        - task: DotNetCoreCLI@2
          displayName: "dotnet build $(buildConfiguration)"
          inputs:
            command: "build"
            arguments: --configuration $(buildConfiguration)
            workingDirectory: src

        - task: DotNetCoreCLI@2
          displayName: "dotnet pack"
          inputs:
            command: "pack"
            arguments: "--configuration $(buildConfiguration)"
            packagesToPack: "src/MNCD/MNCD.csproj"
            nobuild: true
            versioningScheme: "off"

        - task: NuGetCommand@2
          displayName: "nuget push"
          inputs:
            command: "push"
            feedsToUse: "select"
            packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg"
            nuGetFeedType: "internal"
            publishVstsFeed: "MNCD"
            versioningScheme: "off"
            allowPackageConflicts: true
