name: Nuget Package Deploy

on:
  push:
    # branches:
    #  - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - name: Build with dotnet
        run: |
          cd src
          dotnet build --configuration Release
      - name: Test with dotnet
        run: |
          cd src
          dotnet test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set nuget.config password
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "{{"
          tokenSuffix: "}}"
          files: "src/nuget.config"
        env:
          NUGET_ACCESS_PASSWORD: ${{ secrets.NUGET_ACCESS_PASSWORD }}
      - name: Pack nuget Package
        run: |
          cat "./src/nuget.config"
          cd src
          dotnet pack --configuration Release
      - name: Push package to GitHub Packages
        run: |
          cat "./src/nuget.config"
          cd src
          dotnet nuget push **/*.nupkg --source "github"
