name: Nuget Package Deploy

on:
  push:
    # branches:
    #  - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - name: Build with dotnet
        run: dotnet build ./src/MNCD.sln --configuration Release
      - name: Test with dotnet
        run: dotnet test ./src/MNCD.sln
    with:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pack nuget Package
        run: dotnet pack ./src/MNCD.sln --configuration Release
      - name: Push package to GitHub Packages
        run: dotnet nuget push ./src/MNCD/**/*.nupkg --source "github" --api-key "${github-token}"
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    with:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
