name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    name: Build, pack & publish
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Pack
        run: dotnet pack src/MNCD.sln

      - name: Publish
        run: dotnet nuget push src/MNCD/bin/Release/**/*.nupkg --api-key ${{ secrets.NUGET_ORG_API_KEY }} --source https://api.nuget.org/v3/index.json
